# PyTorch란 무엇인가?

Python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 한다.<br/>
* NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우
* 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

책을 통해 구현한 모델에서는...GPU를 안쓰고 CPU를 쓰더라...<br/>
무엇보다도 이번에 연구에서 직접 사용을 해야 하기에...!

## 시작하기
### Tensor

Tensor는 NumPy의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능하다.

In [1]:
from __future__ import print_function
import torch

초기화되지 않은 5x3 행렬을 생성한다

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[9.2756e-39, 9.2755e-39, 8.4490e-39],
        [1.0102e-38, 9.0919e-39, 1.0102e-38],
        [8.9082e-39, 8.4489e-39, 9.6429e-39],
        [8.4490e-39, 9.6429e-39, 9.2755e-39],
        [1.0286e-38, 9.0919e-39, 8.9082e-39]])


**Note** <br/>
초기화되지 않은 행렬이 선언되었지만, 사용하기 전에는 명확히 알려진 값을 포함하고 있지는 않습니다. 초기화되지 않은 행렬이 생성되면 그 시점에 할당된 메모리에 존재하던 값들이 초기값으로 나타납니다.

무작위로 초기화된 행렬을 생성한다.

In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4903, 0.7286, 0.4036],
        [0.4148, 0.9816, 0.8355],
        [0.3506, 0.9854, 0.7236],
        [0.0884, 0.6890, 0.7411],
        [0.2625, 0.0052, 0.4331]])


**이런 의미구나!**<br/>
초기화되지 않은 행렬에 무작위로 값을 생성해 초기화한다<br/>
empty(초기화 되지 않은 행렬)행렬을 선언한 뒤 무작위 값으로 행렬을 초기화 해주는 것이다

dtype이 long이고 0으로 채워진 행렬을 생성한다

In [8]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)  # (5, 3)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


데이터로부터 tensor를 직접 생성한다

In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


또는 존재하는 tensor를 바탕으로 tensor를 만든다. 이 메소드(method)들은 사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들(예. dtype)을 재사용한다.

In [11]:
x = x.new_ones(5, 3, dtype=torch.double)  # new_* 메소드는 크기를 받는다.
print(x)

x = torch.randn_like(x, dtype=torch.float)  # 평균이 0, 분산이 1인 정규분포에서 난수로 채워진
                                            # input과 동일한 크기의 텐서를 반환한다.
                                            # dtype은 오버라이드(Override)하며
                                            # 결과는 동일한 크기를 갖는다
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.0380,  1.8307,  1.0293],
        [-0.3252,  0.2399, -1.3327],
        [-0.0166, -0.1173, -0.0362],
        [ 0.5960, -0.2488, -1.2213],
        [-0.8873,  0.7796,  1.0539]])


행렬의 크기를 구한다.

In [12]:
print(x.size())

torch.Size([5, 3])


**Note**
torch.size는 사실 튜플(tuple)과 같으며, 모든 튜플 연산을 지원한다.

## 연산(Operations)
연산을 위한 여러가지 문법을 제공한다. 다음 예제들을 통해 덧셈 연산을 살펴보자

덧셈: 문법1

In [14]:
x = torch.zeros(5, 3)
# print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-0.0949,  3.2214, -1.1624],
        [-0.1879,  1.5178,  0.0979],
        [-0.4280, -0.2121, -2.7137],
        [ 0.2498, -1.5514,  2.3718],
        [ 1.8634, -1.9733, -0.1913]])


In [16]:
y = torch.rand(5, 3)
print(y)
print('='*40)
print('x+y: ', x+y)

tensor([[0.5764, 0.5294, 0.3395],
        [0.4527, 0.6100, 0.1758],
        [0.4794, 0.7137, 0.9663],
        [0.6410, 0.4902, 0.2482],
        [0.0177, 0.9006, 0.7811]])
x+y:  tensor([[ 0.4816,  3.7509, -0.8229],
        [ 0.2648,  2.1278,  0.2737],
        [ 0.0514,  0.5016, -1.7474],
        [ 0.8908, -1.0612,  2.6200],
        [ 1.8811, -1.0726,  0.5899]])


덧셈: 문법2

In [17]:
print(torch.add(x, y))

tensor([[ 0.4816,  3.7509, -0.8229],
        [ 0.2648,  2.1278,  0.2737],
        [ 0.0514,  0.5016, -1.7474],
        [ 0.8908, -1.0612,  2.6200],
        [ 1.8811, -1.0726,  0.5899]])


덧셈: 결과 tensor를 인자로 제공

In [19]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)  # torch.add() 연산 결과를 result 인자로 제공
print(result)

tensor([[ 0.4816,  3.7509, -0.8229],
        [ 0.2648,  2.1278,  0.2737],
        [ 0.0514,  0.5016, -1.7474],
        [ 0.8908, -1.0612,  2.6200],
        [ 1.8811, -1.0726,  0.5899]])


덧셈: 바꿔치기(In-place)방식

In [20]:
# y에 x 더하기
y.add_(x)
print(y)

tensor([[ 0.4816,  3.7509, -0.8229],
        [ 0.2648,  2.1278,  0.2737],
        [ 0.0514,  0.5016, -1.7474],
        [ 0.8908, -1.0612,  2.6200],
        [ 1.8811, -1.0726,  0.5899]])


NumPy스러운 인덱싱 표기 방법을 사용할 수도 있다

In [21]:
print(x[:, 1])

tensor([ 3.2214,  1.5178, -0.2121, -1.5514, -1.9733])


크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view를 사용한다

In [23]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # -1은 다른 차원들을 사용하여 유추한다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


만약 tensor에 하나의 값만 존재한다면, item()을 사용하면 숫자 값을 얻을 수 있다

In [24]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.1132])
-0.11323907971382141


## NumPy변환(Bridge)
Torch Tensor를 NumPy배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽다<br/>
(CPU 상의) Torch Tensor와 NumPy배열은 **저장 공간을 공유**하기 때문에, 하나를 변경하면 다르 하나도 변경된다.

### Torch Tensor를 NumPy배열로 변환하기

In [25]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


너무 심플하군!

NumPy 배열의 값이 어떻게 변하는지 확인해보자

In [27]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


같은 저장공간을 공유하기 때문에 tensor에 1을 더해도 numpy값이 1씩 더해진다.

### NumPy 배열을 Torch Tensor로 변환하기

NumPy(np)배열을 변경하면 Torch Tensor의 값도 자동 변경되는 것을 확인해보자.

In [28]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)  # numpy배열을 torch로 변환하기 from_numpy:: numpy로 부터~
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Char Tensor를 제외한 CPU상의 모든 Tensor는 NumPy로의 변환을 지원하며, (Numpy에서 Tensor로의) 반대 변환도 지원한다.

## CUDA Tensors

.to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있다.

In [8]:
import torch

In [9]:
import torch
torch.cuda.is_available()

True

In [10]:
x = torch.rand(1)
x

tensor([0.1694])

In [12]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행한다.
# 'torch.device'를 사용하여 tensor를 GPU안팎으로 이동해본다.

if torch.cuda.is_available():
    device = torch.device("cuda")          # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU상에 직접적으로 tensor를 생성하거나
    x = x.to(device)                       # ''.to("cuda")''를 사용하면 된다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ''.tp''는 dtype도 함께 변경한다.
else:
    print("Oooooops!")

tensor([1.1694], device='cuda:0')
tensor([1.1694], dtype=torch.float64)


손글씨 데이터 CUDA로 학습시켜볼까?<br/>
CPU로 2레이어 ConV돌리는데도 진짜 힘들어해서 안쓰러웠어...