# PyTorch란 무엇인가?

Python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 한다.<br/>
* NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우
* 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

책을 통해 구현한 모델에서는...GPU를 안쓰고 CPU를 쓰더라...<br/>
무엇보다도 이번에 연구에서 직접 사용을 해야 하기에...!

다시 Remind하기 위해 내가 작성했던 코드로 되돌아왔다.  -20.03.31.Tue-

## 시작하기
### Tensor

Tensor는 NumPy의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능하다.

In [1]:
from __future__ import print_function
import torch

초기화되지 않은 5x3 행렬을 생성한다

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.2755e-39, 1.0561e-38, 1.0561e-38],
        [9.2755e-39, 9.2756e-39, 9.2755e-39],
        [8.4490e-39, 1.0102e-38, 9.0919e-39],
        [1.0102e-38, 8.9082e-39, 8.4489e-39],
        [9.6429e-39, 8.4490e-39, 9.6429e-39]])


In [3]:
print(x.shape)

torch.Size([5, 3])


**Note** <br/>
초기화되지 않은 행렬이 선언되었지만, 사용하기 전에는 명확히 알려진 값을 포함하고 있지는 않는다.<br>
An uninitialized matrix is declared, but does not contain definite known values before it is used.<br>
초기화되지 않은 행렬이 생성되면 그 시점에 할당된 메모리에 존재하던 값들이 초기값으로 나타납니다.<br>
When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

즉, 초기화 되지 않은 행렬을 생성하면 (행렬 생성시) 할당된 메모리에 존재하던 값들이 초기값으로 나타나는 것이다.

무작위로 초기화된 행렬을 생성한다.

In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5180, 0.3934, 0.9919],
        [0.1476, 0.4832, 0.4823],
        [0.1890, 0.7676, 0.8365],
        [0.2775, 0.7818, 0.9135],
        [0.7667, 0.8947, 0.0473]])


지금까지 수행한 코드<br>

초기화되지 않은 행렬에 무작위로 값을 생성해 초기화한다<br>
empty(초기화 되지 않은 행렬)행렬을 선언한 뒤 무작위 값으로 행렬을 초기화 한다.

dtype이 long이고 0으로 채워진 행렬을 생성한다

In [6]:
x = torch.zeros(5, 3, dtype=torch.long)  # torch.zeros(, dtype) data type을 명시해준다.
print(x)  # (5, 3)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


데이터로부터 tensor를 직접 생성한다

In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


또는 존재하는 tensor를 바탕으로 tensor를 만든다. 이 메소드(method)들은 사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들(예. dtype)을 재사용한다.

In [8]:
x = x.new_ones(5, 3, dtype=torch.double)  # new_* 메소드는 크기를 받는다.
print(x)

x = torch.randn_like(x, dtype=torch.float)  # 평균이 0, 분산이 1인 정규분포에서 난수로 채워진
                                            # input과 동일한 크기의 텐서를 반환한다.
                                            # dtype은 오버라이드(Override)하며
                                            # 결과는 동일한 크기를 갖는다
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1413, -1.0724, -0.1047],
        [ 0.0597, -0.4529, -2.1237],
        [-0.4291,  0.7278, -0.6062],
        [ 1.2161,  1.8543, -0.1888],
        [-0.4907, -0.5059,  0.0828]])


행렬의 크기를 구한다.

In [9]:
print(x.size())

torch.Size([5, 3])


**Note**
torch.size는 사실 튜플(tuple)과 같으며, 모든 튜플 연산을 지원한다.

In [12]:
x.size()[0]

5

## 연산(Operations)
연산을 위한 여러가지 문법을 제공한다. 다음 예제들을 통해 덧셈 연산을 살펴보자

덧셈: 문법1

In [14]:
x = torch.zeros(5, 3)
# print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[-1.0386, -0.6774, -1.8385],
        [-1.3829,  1.4742, -0.6981],
        [-0.6522, -0.9368,  0.1606],
        [ 0.5625,  0.4445,  1.0700],
        [-0.7527, -0.8822, -0.8312]])


In [15]:
y = torch.rand(5, 3)
print(y)
print('='*40)
print('x+y: ', x+y)

tensor([[0.6943, 0.0175, 0.6170],
        [0.2038, 0.8046, 0.7512],
        [0.5024, 0.5574, 0.4745],
        [0.1821, 0.2326, 0.0037],
        [0.9294, 0.8944, 0.1638]])
x+y:  tensor([[-0.3443, -0.6600, -1.2216],
        [-1.1792,  2.2788,  0.0531],
        [-0.1498, -0.3794,  0.6351],
        [ 0.7446,  0.6771,  1.0737],
        [ 0.1767,  0.0121, -0.6674]])


덧셈: 문법2

In [17]:
print(torch.add(x, y))

tensor([[-0.3443, -0.6600, -1.2216],
        [-1.1792,  2.2788,  0.0531],
        [-0.1498, -0.3794,  0.6351],
        [ 0.7446,  0.6771,  1.0737],
        [ 0.1767,  0.0121, -0.6674]])


In [20]:
print(x + y)

tensor([[-0.3443, -0.6600, -1.2216],
        [-1.1792,  2.2788,  0.0531],
        [-0.1498, -0.3794,  0.6351],
        [ 0.7446,  0.6771,  1.0737],
        [ 0.1767,  0.0121, -0.6674]])


In [21]:
print( (x+y) == torch.add(x, y))

tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])


덧셈: 결과 tensor를 인자로 제공

In [22]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)  # torch.add() 연산 결과를 result 인자로 제공
print(result)

tensor([[-0.3443, -0.6600, -1.2216],
        [-1.1792,  2.2788,  0.0531],
        [-0.1498, -0.3794,  0.6351],
        [ 0.7446,  0.6771,  1.0737],
        [ 0.1767,  0.0121, -0.6674]])


In [23]:
# result라는 빈 torch를 만들고, x와 y의 덧셈 결과를 tensor인자로 제공해준다.

덧셈: 바꿔치기(In-place)방식

In [20]:
# y에 x 더하기
y.add_(x)
print(y)

tensor([[ 0.4816,  3.7509, -0.8229],
        [ 0.2648,  2.1278,  0.2737],
        [ 0.0514,  0.5016, -1.7474],
        [ 0.8908, -1.0612,  2.6200],
        [ 1.8811, -1.0726,  0.5899]])


NumPy스러운 인덱싱 표기 방법을 사용할 수도 있다

In [21]:
print(x[:, 1])

tensor([ 3.2214,  1.5178, -0.2121, -1.5514, -1.9733])


크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view를 사용한다

In [25]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # -1은 다른 차원들을 사용하여 유추한다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


만약 tensor에 하나의 값만 존재한다면, item()을 사용하면 숫자 값을 얻을 수 있다

In [27]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.0803])
-1.0803356170654297


## NumPy변환(Bridge)
Torch Tensor를 NumPy배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽다<br/>
(CPU 상의) Torch Tensor와 NumPy배열은 **저장 공간을 공유**하기 때문에, 하나를 변경하면 다르 하나도 변경된다.

### Torch Tensor를 NumPy배열로 변환하기

In [25]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


너무 심플하군!

NumPy 배열의 값이 어떻게 변하는지 확인해보자

In [27]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


같은 저장공간을 공유하기 때문에 tensor에 1을 더해도 numpy값이 1씩 더해진다.

### NumPy 배열을 Torch Tensor로 변환하기

NumPy(np)배열을 변경하면 Torch Tensor의 값도 자동 변경되는 것을 확인해보자.

In [28]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Char Tensor를 제외한 CPU상의 모든 Tensor는 NumPy로의 변환을 지원하며, (Numpy에서 Tensor로의) 반대 변환도 지원한다.

## CUDA Tensors

<code>.to</code> 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있다.

손글씨 데이터 CUDA로 학습시켜볼까?<br/>
CPU로 2레이어 ConV돌리는데도 진짜 힘들어해서 안쓰러웠어...

In [31]:
x

tensor([-1.0803], device='cuda:0')

In [32]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행한다.
# ''torch.device''를 사용하여 tensor를 GPU 안팎으로 이동한다. 


import torch
torch.cuda.is_available()

if torch.cuda.is_available():
    device = torch.device("cuda")         # CUDA 장치 객체9device object)로 GPU상에 직접적으로 tensor를 생성하거나
    y = torch.ones_like(x, device=device)  
    x = x.to(device)                      # .to("cuda")를 사용하면 된단.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))      # .to는 dtype도 함께 변경한다. 
    
else:
    print("OOOOpppps!")
    

tensor([-0.0803], device='cuda:0')
tensor([-0.0803], dtype=torch.float64)


## Reference
https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py