# Deep-Learning-from-Scratch
## Chap5. Backpropagation

### 5.5.1 ReLU 계층

ReLU의 forward()와 backward()함수는 넘파이 배열을 인수로 받는다고 가정한다.

In [3]:
import numpy as np

In [4]:
class ReLU:
    def __init__(self, x):
        self.mask = None
        
    def forward(self, x):     # forward()에서 x는 넘파이 배열을 인수로 받는다.
        self.mask = (x <= 0)  # boolean Indexing: x가 0과 같거나 작은 경우 True를 반환한다.
        x[self.mask] = 0      # mask에 해당하는 원소를 0으로 변경해준다. 
                              # 이는 ReLU함수 적용 결과 0이하의 값에 대해 0으로 반환하는 것과 같다.
        return x
    
    def backward(self, dout):  # backward()에서 dout은 넘파이 배열을 인수로 받는다.
#         print(self.mask)
        dout[self.mask] = 0    # mask에 해당하는 원소, 즉 값이 0보다 작은 경우 역전파때 상류의 값이 하류로 흐르지 않는다.
        dx = dout              # 반면 순전파 때 x가 0보다 크면 역전파때 상류의 값을 그대로 하류로 흘린다.
        return dx

In [5]:
x = np.array([[1.0, -0.5],
              [2.0, 0]])
x

array([[ 1. , -0.5],
       [ 2. ,  0. ]])

In [8]:
activation_Relu = ReLU(x)
print('activation_ReLU_forward(): ')
print(activation_Relu.forward(x))
print("="*40)
print('activation_ReLU_backward(): ')
print(activation_Relu.backward(x))


activation_ReLU_forward(): 
[[1. 0.]
 [2. 0.]]
activation_ReLU_backward(): 
[[1. 0.]
 [2. 0.]]


위와 같이 array x에 들어 있는 값이 0보다 크면(순전파때 x의 값이 0보다 크면) 흘러들어온 gradient가 그대로 흐른다<br/>
반면 array x에 들어 있는 값이 0과 같거나 작은 경우(순전파때 x의 값이 0이하인경우) backward시 값이 전달되지 않는다(0)

여담...<br/>
**파이썬 Class 공부를 좀 더 해야겠다** <br/> 
앞으로 두고두고 많이 사용할 것만 같거든...

위의 ReLU 계층을 구현하기 위해서는 앞서 배웠던 boolean indexing에 대해 이해를 해야 한다.

In [9]:
import numpy as np

x = np.array([[1.0, -0.5], [-2.0, 3.0]])
print(x)

[[ 1.  -0.5]
 [-2.   3. ]]


In [11]:
mask = (x <= 0)
print(mask)

[[False  True]
 [ True False]]


### 5.5.2 Sigmoid 계층

sigmoid 계층 구현

In [15]:
class Sigmoid:
    def __init__(self):
        self.out = None
        
    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out
        return out
    
    def backward(self, dout):
        dx = dout * self.out * (1 - self.out)
        
        return dx

In [16]:
activation_sigmoid = Sigmoid()
print('Sigmoid-forward:',activation_sigmoid.forward(np.array([[1.0, 2.0],[3.0, 4.0]])))
print("="*50)
print('Sigmoid-backward:',activation_sigmoid.backward(np.array([[1.0, 2.0],[3.0, 4.0]])))

Sigmoid-forward: [[0.73105858 0.88079708]
 [0.95257413 0.98201379]]
Sigmoid-backward: [[0.19661193 0.20998717]
 [0.13552998 0.07065082]]


In [17]:
1 / (1 + np.exp(-1.0))

0.7310585786300049